apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kn-py-psql-vmdata-fn
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: quay.io/rguske/kn-py-psql-vmdata-fn:v1.0
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: psql-secret
                  key: db_host
            - name: DB_PORT
              valueFrom:
                secretKeyRef:
                  name: psql-secret
                  key: db_port
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: psql-secret
                  key: db_name
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: psql-secret
                  key: db_user
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: psql-secret
                  key: db_password
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: trigger-kn-py-psql-vmdata-fn-add
  labels:
    eventing.knative.dev/broker: inmem-broker-transformer
spec:
  broker: inmem-broker-transformer
  filter:
    attributes:
      type: "dev.knative.apiserver.resource.add"
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: kn-py-psql-vmdata-fn
  delivery:
    retry: 3
    backoffPolicy: linear
    backoffDelay: PT5S
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: trigger-kn-py-psql-vmdata-fn-delete
  labels:
    eventing.knative.dev/broker: inmem-broker-transformer
spec:
  broker: inmem-broker-transformer
  filter:
    attributes:
      type: "dev.knative.apiserver.resource.delete"
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: kn-py-psql-vmdata-fn
  delivery:
    retry: 3
    backoffPolicy: linear
    backoffDelay: PT5S
