apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kn-ps-cloudevent-slack
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "1"
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: rguske/kn-ps-cloudevent-slack:1.0
          envFrom:
            - secretRef:
                name: cloudevent-slack-secret
          env:
            - name: FUNCTION_DEBUG
              value: "false"
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: kn-ps-cloudevent-slack-trigger
spec:
  broker: rabbitmq-broker
  filter:
    attributes:
      type: my.very.own.cloudevent.created.v0
  subscriber:
    ref:
      apiVersion: serving.knative.dev/v1
      kind: Service
      name: kn-ps-cloudevent-slack
