apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: kn-dev-py-asop-webhook-sinkbinding
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    name: kn-dev-py-asop-webhook
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: rabbitmq-broker
